apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: demo-pipeline
description: Sample pipeline to deploy to Cloud Run
serialPipeline:
  stages:
    - targetId: dev
      profiles: []
