apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: demo-pipeline
description: Cloud Run pipeline for Python app
serialPipeline:
  stages:
    - targetId: dev
      profiles: [dev]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Cloud Run dev environment
run:
  location: projects/responsive-seat-459809-g5/locations/us-central1/services/demo-pipeline-dev

