apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: demo-pipeline
description: Cloud Run pipeline for Python app
serialPipeline:
  stages:
    - targetId: dev
      profiles: [dev]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: Cloud Run dev environment
run:
  location: location: us-central1

