apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app-dev
spec:
  template:
    spec:
      containers:
      - image: app  # This is the placeholder Cloud Deploy replaces
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
