apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: $_SERVICE_NAME
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: demoapi
          resources:
            limits:
              cpu: 1000m
              memory: 128Mi
