apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: cloud-run-app

build:
  artifacts:
    - image: $_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_SERVICE_NAME

profiles:
  - name: dev
    deploy:
      cloudrun:
        region: $_DEPLOY_REGION
        projectId: $PROJECT_ID
    manifests:
      rawYaml:
        - deploy-dev.yaml
