apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: $_SERVICE_NAME
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: $_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_SERVICE_NAME:$COMMIT_SHA
          resources:
            limits:
              cpu: 1000m
              memory: 128Mi
