apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: cloud-run-app

build:
  artifacts:
  - image: '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_SERVICE_NAME:$COMMIT_SHA'

profiles:
- name: dev
  manifests:
    rawYaml:
    - deploy-dev.yaml
  deploy:
    cloudrun:
      region: $_DEPLOY_REGION
