apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: demo-app1

build:
  artifacts:
  - image: us-central1-docker.pkg.dev/responsive-seat-459809-g5/cloud-run-source-deploy/demoapi

profiles:
- name: dev
  manifests:
    rawYaml:
    - deploy-dev.yaml
  deploy:
    cloudrun:
      region: us-central1
    
