apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: demo-app1

build:
  artifacts:
  - image: demoapi  

profiles:
- name: dev
  manifests:
    rawYaml:
    - deploy-dev.yaml
  deploy:
    cloudrun:
      region: $_DEPLOY_REGION
