apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: demo-app
build:
  artifacts:
    - image: '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPO/$_SERVICE_NAME:$COMMIT_SHA'
deploy:
  cloudRun:
    projectId: $PROJECT_ID
    region: $_DEPLOY_REGION
    service: $_SERVICE_NAME
