
apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: demo-app

build:
  artifacts:
    - image: us-central1-docker.pkg.dev/PROJECT_ID/REPO_NAME/demoapi
  tagPolicy:
    gitCommit: {}

profiles:
  - name: dev
    manifests:
      rawYaml:
        - deploy-dev.yaml
    deploy:
      cloudrun:
        serviceName: demoapi
        region: us-central1
