apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: java-app
build:
  artifacts:
    - image: us-central1-docker.pkg.dev/responsive-seat-459809-g5/java-app-repo/java-app
deploy:
  cloudrun:
    projectId: responsive-seat-459809-g5
    region: us-central1
    serviceName: java-app
